export const IS_FETCHING = "IS_FETCHING";
export const DONE_FETCHING = "DONE_FETCHING";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_GLOBAL = "FETCH_GLOBAL";
export const FETCH_SELECTED_COUNTRY = "FETCH_SELECTED_COUNTRY";
export const SET_COUNTRY_STATUS = "SET_COUNTRY_STATUS";
export const SET_GLOBAL_STATUS = "SET_GLOBAL_STATUS";
export const SET_STATISTICS = "SET_STATISTICS";
